### ISSUE TITLE
Lagalista not working

### ISSUE THREAD

**Issue by Franz321** [alexthemaster/lagalista#15]
Hey, I wanted to use your program but I get an error message. I replaced all the ID's with X's equal to their leangth (maybe I inputed something wrong there, this way you can maybe determen that).

`Web server started on port 8080
? Choose what action you want to do Show config
{
  spotifyClientID: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  spotifySecret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  deezerAppID: 'XXXXXX',
  deezerSecretKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  playlists: [
    {
      spotifyPlaylist: '4p69uao38JLy1hYJ7mHLir',
      deezerPlaylist: 'sKVvwPmaCR4iYsBB6'
    }
  ]
}
? Choose what action you want to do Convert playlists
Please log into Deezer using the following URL and then re - select this action: https://connect.deezer.com/oauth/auth.php?app_id=551242&redirect_uri=http://localhost:8080/callback&perms=manage_library

? Choose what action you want to do Convert playlists
WARNING: Deezer has an API limit of 50 interactions / 5 seconds therefore this process could take some time.
Found 296 tracks in the Spotify playlist called 2020, adding them to Deezer!
file:///C:/Users/X/lagalista/src/index.mjs:114
                const tracks = data.map(track => track.id);
                                    ^

TypeError: Cannot read properties of undefined (reading 'map')
    at file:///C:/Users/X/lagalista/src/index.mjs:114:37
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (file:///C:/Users/X/lagalista/node_modules/p-queue/dist/index.js:109:36)`

**Comment by alexthemaster** [comment]
Is your Deezer playlist empty by chance?

**Comment by Franz321** [comment]
Hey, thank you for the quick answer. Yes, the playlist was empty
Now I have a problem even before I get asked to input my playlists. This time I will leave the ID and secret blank ^^. maybe its my mistake after all, but it dosnt look like it.

> C:\Users\X>git clone https://github.com/alexthemaster/lagalista.git
> Cloning into 'lagalista'...
> remote: Enumerating objects: 87, done.
> remote: Counting objects: 100% (9/9), done.
> remote: Compressing objects: 100% (9/9), done.
> remote: Total 87 (delta 0), reused 0 (delta 0), pack-reused 78
> Receiving objects: 100% (87/87), 112.54 KiB | 5.63 MiB/s, done.
> Resolving deltas: 100% (49/49), done.
> 
> C:\Users\Franz>cd lagalista
> 
> C:\Users\X\lagalista>npm install
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> 
> added 136 packages, and audited 137 packages in 9s
> 
> 27 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> C:\Users\X\lagalista>npm start
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> 
> `>` start
> `>` node src/index.mjs
> 
> Web server started on port 8080
> There doesn't seem to be a config file available, creating one...
> ? What is your Spotify app id? 8806de4d0e3f4716813558664a68d9fa
> ? What is your Spotify client secret? 23fbc0c9d83d472a99f75effe10ae8f0
> ? What is your Deezer app id? 551242
> ? What is your Deezer secret key? c7b48e7aeb737cc264be99059839da37
> ![Unb1enannt](https://user-images.githubusercontent.com/37617308/179046635-697f1177-0d83-4ed7-be90-66acdfb99026.PNG)
> ![Unbenannt](https://user-images.githubusercontent.com/37617308/179046638-78efb9fa-bde1-4415-a83b-b27d118d3175.PNG)
> 
> C:\Users\X\lagalista\node_modules\spotify-web-api-node\src\http-manager.js:43
>     return new WebapiAuthenticationError(response.body, response.headers, response.statusCode);
>            ^
> 
> WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.
> Details: temporarily_unavailable.
>     at _toError (C:\Users\X\lagalista\node_modules\spotify-web-api-node\src\http-manager.js:43:12)
>     at C:\Users\X\lagalista\node_modules\spotify-web-api-node\src\http-manager.js:71:25
>     at Request.callback (C:\Users\X\lagalista\node_modules\superagent\lib\node\index.js:905:3)
>     at C:\Users\X\lagalista\node_modules\superagent\lib\node\index.js:1127:20
>     at IncomingMessage.<anonymous> (C:\Users\X\lagalista\node_modules\superagent\lib\node\parsers\json.js:22:7)
>     at Stream.emit (node:events:527:28)
>     at Unzip.<anonymous> (C:\Users\X\lagalista\node_modules\superagent\lib\node\unzip.js:53:12)
>     at Unzip.emit (node:events:527:28)
>     at endReadableNT (node:internal/streams/readable:1345:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   body: { error: 'temporarily_unavailable', error_description: '' },
>   headers: {
>     date: 'Thu, 14 Jul 2022 17:17:43 GMT',
>     'content-type': 'application/json',
>     'set-cookie': [
>       '__Host-device_id=AQDAAYrwv2Q_SBXB16JcGwreO7afONuvy8sSnuvvaU3s7hRMbCgy15euclkGDkJJo8YKQkDUDX1j0ICecp7Ezpu9qsZGXM6Uo9o;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax',
>       'sp_tr=false;Version=1;Domain=accounts.spotify.com;Path=/;Secure;SameSite=Lax'
>     ],
>     'sp-trace-id': 'edda15540ef9b3ba',
>     'strict-transport-security': 'max-age=31536000',
>     'x-content-type-options': 'nosniff',
>     'content-encoding': 'gzip',
>     vary: 'Accept-Encoding',
>     server: 'envoy',
>     via: 'HTTP/2 edgeproxy, 1.1 google',
>     'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
>     connection: 'close',
>     'transfer-encoding': 'chunked'
>   },
>   statusCode: 503
> }
> 
> C:\Users\X\lagalista>npm start
> npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> 
> `>` start
> `>` node src/index.mjs
> 
> Web server started on port 8080
> node:internal/process/promises:279
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> Error: getaddrinfo EAI_AGAIN accounts.spotify.com
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
>   errno: -3001,
>   code: 'EAI_AGAIN',
>   syscall: 'getaddrinfo',
>   hostname: 'accounts.spotify.com',
>   response: undefined
> }
> 
> C:\Users\X\lagalista>

**Comment by alexthemaster** [comment]
By the looks of it Spotify's API is currently unavailable, try again later maybe?

**Comment by Franz321** [comment]
you are right, it worked now. At least kind of. It says that it successfully converted but when I visit my Deezer account, nothing changed. Do I have to past the hole link of the playlist maybe?

`Web server started on port 8080
? Choose what action you want to do Convert playlists
Can't convert because there aren't any playlists available. Please add some!
? Choose what action you want to do Add playlist
? What is the ID of the Spotify playlist? 4p69uao38JLy1hYJ7mHLir
? What is the ID of the Deezer playlist equivalent to the Spotify playlist? sKVvwPmaCR4iYsBB6
Successfully added a new playlist!
? Choose what action you want to do Convert playlists
Please log into Deezer using the following URL and then re - select this action: https://connect.deezer.com/oauth/auth.php?app_id=551242&redirect_uri=http://localhost:8080/callback&perms=manage_library

? Choose what action you want to do Convert playlists
WARNING: Deezer has an API limit of 50 interactions / 5 seconds therefore this process could take some time.
Found 296 tracks in the Spotify playlist called 2020, adding them to Deezer!
Successfully updated the sKVvwPmaCR4iYsBB6 Deezer playlist!`

**Comment by alexthemaster** [comment]
That's weird... the playlist ID is all it needs 🤔

**Comment by alexthemaster** [comment]
On second look, something doesn't seem right! 
A Deezer playlist ID consists of only numbers. You can find yours at the final of the URL when you access the playlist with a browser.
![image](https://user-images.githubusercontent.com/31011461/179050067-7fe825d9-1485-4d50-9368-8511db9b74b5.png)

**Comment by Franz321** [comment]
Oh, I took it from the shar link, I will try it again, ty

**Comment by alexthemaster** [comment]
It doesn't have an error output, no, but I will try to implement it in a couple of days. Good to know it works!

**Comment by Franz321** [comment]
That sounds good, cool that it works, looking forward to the error output. Thanks again :)
